# ─── Datasource ──────────────────────────────────────────────────────────────
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=${DB_USER}
%prod.quarkus.datasource.password=${DB_PASSWORD}
%prod.quarkus.datasource.jdbc.url=${DB_URL}

# ─── Hibernate ORM ───────────────────────────────────────────────────────────
# validate: Flyway gerencia o schema; Hibernate apenas verifica a consistência
%prod.quarkus.hibernate-orm.database.generation=validate
# %prod.quarkus.hibernate-orm.database.generation=none

# ─── Flyway ──────────────────────────────────────────────────────────────────
%prod.quarkus.flyway.migrate-at-start=true
%prod.quarkus.flyway.locations=classpath:db/migration
%prod.quarkus.flyway.baseline-on-migrate=true

# ─── CORS ────────────────────────────────────────────────────────────────────
quarkus.http.cors=true
quarkus.http.cors.origins=${CORS_ORIGINS}
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Accept,Authorization,Content-Type,Origin
quarkus.http.cors.access-control-allow-credentials=true

# ─── Redis ───────────────────────────────────────────────────────────────────
%prod.quarkus.redis.hosts=${REDIS_URL}
# se não usar Redis de fato no MVP, comente a linha acima e desative o healthcheck:
%prod.quarkus.redis.health.enabled=true

# ─── JWT ─────────────────────────────────────────────────────────────────────
mp.jwt.verify.issuer=https://event-ten-delta.vercel.app/
# %dev.mp.jwt.verify.publickey.location=publicKey.pem
%prod.mp.jwt.verify.publickey=${JWT_PUBLIC_KEY}

# %dev.smallrye.jwt.sign.key.location=privateKey.pem
%prod.smallrye.jwt.sign.key=${JWT_PRIVATE_KEY}

smallrye.jwt.new-token.issuer=https://event-ten-delta.vercel.app/
smallrye.jwt.new-token.lifespan=86400

# ─── CORS ────────────────────────────────────────────────────────────────────
%prod.quarkus.http.cors.origins=${CORS_ORIGINS}


# docker run --rm -p 8080:8080 \
#   -e DB_URL="jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require" \
#   -e DB_USER="postgres.iioxjzvobhzqiqchhhoy" \
#   -e DB_PASSWORD="Legonardo123" \
#   -e REDIS_URL="redis://default:gQAAAAAAASzZAAIgcDJjYTVmMzllMDAzMjE0N2FiOGNjMjQ3YmU2ZTRhNDQ3Mw@active-panda-77017.upstash.io:6379" \
#   -e JWT_PUBLIC_KEY="$(cat api/src/main/resources/publicKey.pem)" \
#   -e JWT_PRIVATE_KEY="$(cat api/src/main/resources/privateKey.pem)" \
#   -e CORS_ORIGINS="https://event-ten-delta.vercel.app/" \
#   leonardomilv3/eventing-api:1.1
